GET https://omni-technical-challange.onrender.com/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiY2FpcXVlIHRlc3RlNCIsImlhdCI6MTcyOTg3OTg4NiwiZXhwIjoxNzI5ODgyODg2fQ.9br4Qp773npZClq5R3v3Ev6fYjcSf7ndtnZrOSXztBo

###
POST https://omni-technical-challange.onrender.com/users/signup
content-type: application/json

{
    "username": "caique test24",
    "password": "1234",
    "birthdate": "12/02/1999"
}

###
POST https://omni-technical-challange.onrender.com/users/signin
content-type: application/json

{
    "username": "caique teste4",
    "password": "1234"
}

###
POST  https://omni-technical-challange.onrender.com/transfer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiY2FpcXVlIHRlc3RlNCIsImlhdCI6MTcyOTg3OTg4NiwiZXhwIjoxNzI5ODgyODg2fQ.9br4Qp773npZClq5R3v3Ev6fYjcSf7ndtnZrOSXztBo
content-type: application/json

{
  "fromId": "1",
  "toId": "2",
  "amount": 100
}

