GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInVzZXJuYW1lIjoiY2FpcXVlIHRlc3RlNCIsImlhdCI6MTcyOTgwNDYyOCwiZXhwIjoxNzI5ODA0Njg4fQ.GNqMrMYhuNHGzL9TWZ3lq4t7xXJGyW_AwDIu-n8oHsc

###
POST http://localhost:3000/users/signup
content-type: application/json

{
    "username": "caique teste4",
    "password": "1234",
    "birthdate": "12/02/1999"
}

###
POST http://localhost:3000/users/signin
content-type: application/json

{
    "username": "caique teste4",
    "password": "1234"
}
